version: 2

project_name: secrets-lambda-extension

builds:
  - binary: bin/secrets
    main: secrets.go
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    # See https://go.dev/doc/install/source#environment for valid GOOS and GOARCH combinations
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "amd64"
      - "arm64"
      - "arm"
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: "arm"
      - goos: windows
        goarch: "arm"

checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}.sha256sum'

snapshot:
  version_template: "{{ .Tag }}-dev"

archives:
  - formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md
      - src: scripts/*
        strip_parent: true

changelog:
  disable: true

release:
  github:
    owner: CruGlobal
    name: secrets-lambda-extension
  skip_upload: false
